# Base image with Linux - Ubuntu
# change this to kali
FROM ubuntu:latest 

# Install OpenSSH Server and other required packages
RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Enable password authentication for SSH
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Set a default root password (root:password)
RUN echo 'root:password' | chpasswd

# Create a directory for the script
WORKDIR /app

# Copy the script file to the container
COPY pimpmykali.sh .

# Expose port 22 for SSH access
EXPOSE 22

# Start the SSH server and run the script
CMD service ssh start && ./pimpmykali.sh
